-- Real authenticated RLS and transactions, no persistent fixtures.
begin;
insert into auth.users(id,email) values(gen_random_uuid(),'formula-categories-'||gen_random_uuid()||'@example.invalid');
select set_config('request.jwt.claim.sub',id::text,true) from auth.users where email like 'formula-categories-%@example.invalid' order by created_at desc nulls first limit 1;
set local role authenticated;
do $$
declare
  u uuid:=auth.uid(); pid uuid; other uuid; material uuid; calc uuid;
  target text; source text; failed boolean; before_count integer;
begin
  assert not has_table_privilege('anon','public.product_categories','SELECT'),'anonymous table grant';
  assert not has_table_privilege('authenticated','public.product_categories','TRUNCATE'),'truncate bypasses RLS';
  assert not has_table_privilege('authenticated','public.product_categories','DELETE'),'hard deletion of tombstones';
  perform public.list_product_categories('[{"id":"Еще","label":"Еще"}]');
  assert (select count(*)=7 from public.product_categories where user_id=u and deleted_at is null),'initial categories/legacy';
  perform public.remove_product_category('Еще');
  perform public.list_product_categories('[{"id":"Еще","label":"Еще"}]');
  assert (select deleted_at is not null from public.product_categories where user_id=u and id='Еще'),'legacy resurrected';
  perform public.remove_product_category('notebooks');
  perform public.list_product_categories();
  assert (select deleted_at is not null from public.product_categories where user_id=u and id='notebooks'),'default resurrected';
  source:=public.create_product_category('Тестовый раздел');
  target:=public.create_product_category('Куда перенести');
  failed:=false;
  begin perform public.create_product_category(' тестовый раздел '); exception when others then failed:=true; end;
  assert failed,'duplicate category';
  insert into public.products(user_id,name,product_category,work_hours,markup_percent) values(u,'Первое',source,1,120) returning id into pid;
  insert into public.products(user_id,name,product_category) values(u,'Второе',source) returning id into other;
  failed:=false;
  begin perform public.remove_product_category(source,null,false,array[pid,other]); exception when others then failed:=true; end;
  assert failed,'deletion without confirmation';
  failed:=false;
  begin perform public.remove_product_category(source,target,false,array[pid]); exception when others then failed:=true; end;
  assert failed and (select count(*)=2 from public.products where product_category=source and user_id=u),'stale confirmation partially moved products';
  failed:=false;
  begin perform public.remove_product_category(source,source,false,array[pid,other]); exception when others then failed:=true; end;
  assert failed,'move to self';
  failed:=false;
  begin perform public.remove_product_category(source,'notebooks',false,array[pid,other]); exception when others then failed:=true; end;
  assert failed,'move to deleted destination';
  assert public.remove_product_category(source,target,false,array[other,pid])=2,'transfer count';
  assert (select count(*)=2 from public.products where product_category=target and user_id=u and is_active),'transfer';
  assert (select work_hours=1 and markup_percent=120 from public.products where id=pid),'transfer changed pricing';
  failed:=false;
  begin insert into public.products(user_id,name,product_category) values(u,'Устаревшая вкладка',source); exception when others then failed:=true; end;
  assert failed,'stale tab resurrected removed category';
  failed:=false;
  begin update public.products set product_category=source where id=pid; exception when others then failed:=true; end;
  assert failed,'stale move into removed category';
  insert into public.materials(user_id,name,unit,package_cost,package_quantity) values(u,'Тест: смола','g',1000,500) returning id into material;
  insert into public.stock_movements(user_id,material_id,movement_type,source_type,quantity_delta) values(u,material,'receipt','manual',1000);
  insert into public.product_materials(user_id,product_id,material_id,quantity_per_unit) values(u,pid,material,35);
  calc:=public.produce_selected_tools(pid,1,'[]',null,gen_random_uuid(),'[]');
  select count(*) into before_count from public.product_stock_movements where product_id=pid;
  assert public.remove_product_category(target,null,true,array[pid,other])=2,'deletion count';
  assert (select count(*)=2 from public.products where id in (pid,other) and not is_active),'deleted cards active';
  assert exists(select 1 from public.production_calculations where id=calc and product_id=pid),'production history erased';
  assert exists(select 1 from public.product_batches where product_id=pid),'batch history erased';
  assert (select count(*)=before_count from public.product_stock_movements where product_id=pid),'stock history erased';
  assert (select current_stock=965 from public.materials where id=material),'deletion consumed or restored raw materials';
  perform public.list_product_categories();
  assert (select deleted_at is not null from public.product_categories where user_id=u and id=target),'deleted products restored category';
  failed:=false;
  begin update public.products set is_active=true where id=pid; exception when others then failed:=true; end;
  assert failed,'archived product resurrected deleted category';
  -- Reuse a name without restoring archived products.
  assert public.create_product_category('Тестовый раздел')<>source,'reused tombstone';
  perform set_config('request.jwt.claim.sub',gen_random_uuid()::text,true);
  assert not exists(select 1 from public.product_categories where user_id=u),'cross-account read';
  failed:=false;
  begin perform public.remove_product_category('coasters'); exception when others then failed:=true; end;
  assert failed,'cross-account category deletion';
  failed:=false;
  begin insert into public.product_categories(user_id,id,label) values(u,'intruder','intruder'); exception when others then failed:=true; end;
  assert failed,'cross-account insertion';
  perform set_config('request.jwt.claim.sub',u::text,true);
  assert (select deleted_at is null from public.product_categories where user_id=u and id='coasters'),'foreign change succeeded';
end $$;
reset role;
rollback;
select 'Category tests passed; all fixtures rolled back' as result;
